name: 'Build HTML'
description: 'A simple GitHub Action for producing build artifacts compatible with html'
author: 'Portella'
runs:
  using: "composite"
  steps:
    - name: dotnet restore
      shell: bash
      run: echo "Hi"
