name: 'Build HTML'
description: 'A simple GitHub Action for producing build artifacts compatible with html'
author: 'Portella'
inputs:
  origin-path:  # id of input
    description: 'origin to build'
    required: true
    default: ./
runs:
  using: "composite"
  steps:
    - name: log
      shell: bash
      run: ls ${{ inputs.origin-path }}  
    - name: Run
      shell: bash
      run: cd $GITHUB_ACTION_PATH/console; ls; dotnet restore; dotnet build; dotnet run $ORIGIN_PATH;    
