name: 'Build HTML'
description: 'A simple GitHub Action for producing build artifacts compatible with html'
author: 'Portella'
runs:
  using: "composite"
  steps:
    - name: Move to console
      shell: bash
      run: echo ORIGIN_PATH=./ >> $GITHUB_ENV;  
    - name: Run
      shell: bash
      run: cd $GITHUB_ACTION_PATH/console; ls; dotnet restore; dotnet build; dotnet run $ORIGIN_PATH;    
