name: 'Build HTML'
description: 'A simple GitHub Action for producing build artifacts compatible with html'
author: 'Portella'
runs:
  using: "composite"
  steps:
    - name: Restore
      shell: bash
      run: ls
    - name: Restore
      shell: bash
      run: dotnet restore $GITHUB_ACTION_PATH
    - name: Restore
      shell: bash
      run: dotnet build
      
