name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["feature/*"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and run unit tests
        run: |
          cd builder
          dotnet build -c Release
          dotnet test
